apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: intikepri-openbao
  labels:
    app.kubernetes.io/name: intikepri-openbao
    app.kubernetes.io/part-of: intikepri
    app.kubernetes.io/managed-by: flux
spec:
  provider:
    vault:
      server: http://intikepri-openbao.intikepri-openbao.svc:8200
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: external-secrets
            namespace: flux-system
