apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intikepri-static-webhook
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: intikepri-openbao
    kind: ClusterSecretStore
  target:
    name: intikepri-static-webhook
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kv/intikepri-static/webhook-token
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intikepri-cms-webhook
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: intikepri-openbao
    kind: ClusterSecretStore
  target:
    name: intikepri-cms-webhook
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kv/intikepri-cms/webhook-token
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intikepri-infra-webhook
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: intikepri-openbao
    kind: ClusterSecretStore
  target:
    name: intikepri-infra-webhook
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: kv/intikepri-infra/webhook-token
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: intikepri-minio
  namespace: intikepri-minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: intikepri-openbao
    kind: ClusterSecretStore
  target:
    name: intikepri-minio
    deletionPolicy: Retain
  data:
    - secretKey: rootUser
      remoteRef:
        key: kv/intikepri-cms/minio
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: kv/intikepri-cms/minio
        property: rootPassword
